//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace akademik_ccdp.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class akademik_dbEntities1 : DbContext
    {
        public akademik_dbEntities1()
            : base("name=akademik_dbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<instruktur> instrukturs { get; set; }
        public DbSet<mahasiswa> mahasiswas { get; set; }
        public DbSet<matakuliah> matakuliahs { get; set; }
        public DbSet<nilai> nilais { get; set; }
        public DbSet<pengajaran> pengajarans { get; set; }
        public DbSet<program> programs { get; set; }
        public DbSet<user> users { get; set; }
    }
}
