//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace akademik_ccdp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class instruktur
    {
        public instruktur()
        {
            this.pengajarans = new HashSet<pengajaran>();
        }
    
        public string kode_instruktur { get; set; }
        public string nama { get; set; }
        public string alamat { get; set; }
        public string telp { get; set; }
    
        public virtual ICollection<pengajaran> pengajarans { get; set; }
    }
}
