//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace akademik_ccdp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class mahasiswa
    {
        public mahasiswa()
        {
            this.nilais = new HashSet<nilai>();
        }
    
        public string nim { get; set; }
        public string kode_program { get; set; }
        public string nama { get; set; }
        public Nullable<System.DateTime> tgl_lahir { get; set; }
        public string alamat { get; set; }
        public string telp { get; set; }
    
        public virtual program program { get; set; }
        public virtual ICollection<nilai> nilais { get; set; }
    }
}
