//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace akademik_ccdp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class pengajaran
    {
        public pengajaran()
        {
            this.nilais = new HashSet<nilai>();
        }
    
        public int kode_pengajaran { get; set; }
        public string kode_instruktur { get; set; }
        public string kode_matakuliah { get; set; }
    
        public virtual instruktur instruktur { get; set; }
        public virtual matakuliah matakuliah { get; set; }
        public virtual ICollection<nilai> nilais { get; set; }
    }
}
